application: uiucscheduler
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: lxml
  version: "latest"

handlers:
- url: /static
  static_dir: static

- url: /update
  script: main.app
  login: admin
    
- url: /.*
  script: main.app

